package io.shivamvk.networklibrary.model.profile

data class User (

	val _id : String,
	val checkbox1 : Checkbox1,
	val checkbox2 : Checkbox2,
	val checkbox3 : Checkbox3,
	val checkbox4 : Checkbox4,
	val checkbox5 : Checkbox5,
	val available : Boolean,
	val location : List<String>,
	val languages : List<Languages>,
	val symptoms : List<String>,
	val active : Boolean,
	val userType : String,
	val full_name : String,
	val email : String,
	val verified : Boolean,
	val boardExpiration : String,
	val college : String,
	val education : String,
	val gender : String,
	val licenseExpiration : String,
	val malpracticeLawsuites : Boolean,
	val medicalBoardDeciplinaryAction : Boolean,
	val professionalStatement : String,
	val stateLicense : String,
	val yearsOfExperience : String,
	val bank : Bank?,
	val boardCertified : Boolean,
	val country : String,
	val deaLicenseExpirationDate : String,
	val deaLicenseNumber : String,
	val dob : String,
	val medicalLicenseExpiration : String,
	val medicalLicenseNumber : String,
	val medicalLicenseState : String,
	val medicalLicenseType : String,
	val mobileNumber : String,
	val postalCode : String,
	val kyc : Kyc?,
	val profile_picture : String
)